// SECRETS.H TAMPLATE
// AO PREENCHER, NÃO SUBA PARA O GITHUB! AQUI SERÃO COLOCADAS INFORMAÇÕES SENSÍVEIS

#include <pgmspace.h>

#define SECRET
#define THINGNAME "INSIRA O NOME DA THING CRIADA NO AWS IOT CORE AQUI"

const char WIFI_SSID[]        = "INSIRA O NOME DA REDE WIFI AQUI";
const char WIFI_PASSWORD[]    = "INSIRA A SENHA DA REDE WIFI AQUI";    
const char AWS_IOT_ENDPOINT[] = "INSIRA O ENDPOINT DO AWS IOT CORE AQUI";

// Amazon Root CA 1
static const char AWS_CERT_CA[] PROGMEM = "INSIRA O CERTIFICADO AQUI";

// Device Certificate
static const char AWS_CERT_CRT[] PROGMEM = "INSIRA O CERTIFICADO AQUI";

// Device Private Key
static const char AWS_CERT_PRIVATE[] PROGMEM = "INSIRA O CERTIFICADO AQUI";